//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Библиотечной_информационная_система.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public location()
        {
            this.Library_Card = new HashSet<Library_Card>();
        }
    
        public int rack { get; set; }
        public int sthelf { get; set; }
        public int id_discipline { get; set; }
        public int id_date_of_publication { get; set; }
        public int id_book { get; set; }
        public int id { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Date_of_publication Date_of_publication { get; set; }
        public virtual Discipline Discipline { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Library_Card> Library_Card { get; set; }
    }
}
