//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Библиотечной_информационная_система.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int id { get; set; }
        public int id_worker { get; set; }
        public int id_library_card { get; set; }
    
        public virtual Library_Card Library_Card { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
